"""
Centralized configuration for the Legal_QA inference API.

All paths default to the flagship HKG+PC+RL / Employment_Labour / actionable
experiment directory.  Override via environment variables or by editing
DEFAULT_DATA_DIR below.
"""

import os

# Configure HuggingFace to use a local cache directory inside the repository
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.environ["HF_HOME"] = os.path.join(_REPO_ROOT, ".hf_cache")

import torch

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# ── Default data directory (flagship experiment) ────────────────────────────
DEFAULT_DATA_DIR = os.environ.get(
    "LEGAL_QA_DATA_DIR",
    os.path.join(_REPO_ROOT, "HKG+PC+RL", "Employment_Labour", "actionable"),
)


def _data_path(filename: str) -> str:
    """Resolve a filename relative to the data directory."""
    return os.path.join(DEFAULT_DATA_DIR, filename)


# ── Inference configuration ─────────────────────────────────────────────────
INFERENCE_CONFIG = {
    # ── paths (resolved to the data directory) ──────────────────────────────
    "rl_model_path":        _data_path("rl_policy_model.pt"),
    "dssm_model_path":      _data_path("dssm_model.pt"),
    "retrieval_index":      _data_path("dssm_retrieval_index.pt"),
    "node_emb_cache_path":  _data_path("node_embeddings.pt"),
    "kg_path":              _data_path("edges.csv"),
    "nodes_csv_path":       _data_path("nodes.csv"),

    # ── retrieval ───────────────────────────────────────────────────────────
    "top_k":                3,
    "dssm_candidate_k":     20,
    "use_cross_encoder_rerank": True,
    "use_bm25_fallback":    True,
    "mmr_lambda":           0.6,

    # ── RL inference ────────────────────────────────────────────────────────
    "rl_test_steps":        4,
    "use_chain_query_expand": True,

    # ── seed chain discovery (TF-IDF over KG node labels) ───────────────────
    "seed_top_k_candidates": 30,
    "seed_max_chain_len":    4,

    # ── LLM ─────────────────────────────────────────────────────────────────
    "llm_backend":          os.environ.get("LLM_BACKEND", "openai"),
    "groq_api_key":         os.environ.get("GROQ_API_KEY", ""),
    "groq_model":           os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile"),
    "openai_api_key":       os.environ.get("OPENAI_API_KEY", ""),
    "openai_model":         os.environ.get("OPENAI_MODEL", "gpt-4o"),
    "ollama_model":         os.environ.get("OLLAMA_MODEL", "llama3"),
    "ollama_url":           os.environ.get("OLLAMA_URL", "http://localhost:11434/api/generate"),
    "hf_model":             os.environ.get("HF_MODEL", "microsoft/phi-2"),
    "temperature":          0.4,
    "top_p":                0.9,
    "max_new_tokens":       512,

    # ── misc ────────────────────────────────────────────────────────────────
    "bert_model":           "law-ai/InLegalBERT",
    "seed":                 42,
    "device":               "cuda" if torch.cuda.is_available() else "cpu",
}


def get_required_files() -> list[dict]:
    """Return a list of required files with their paths and descriptions."""
    return [
        {
            "path": INFERENCE_CONFIG["rl_model_path"],
            "name": "rl_policy_model.pt",
            "description": "Trained PPO RL policy model (generated by train_rl.py)",
        },
        {
            "path": INFERENCE_CONFIG["dssm_model_path"],
            "name": "dssm_model.pt",
            "description": "Trained DSSM retrieval model (generated by train_dssm.py)",
        },
        {
            "path": INFERENCE_CONFIG["retrieval_index"],
            "name": "dssm_retrieval_index.pt",
            "description": "Pre-computed retrieval embeddings and DB data (generated by train_dssm.py)",
        },
        {
            "path": INFERENCE_CONFIG["node_emb_cache_path"],
            "name": "node_embeddings.pt",
            "description": "Pre-computed BERT embeddings for KG nodes (generated during training)",
        },
        {
            "path": INFERENCE_CONFIG["kg_path"],
            "name": "edges.csv",
            "description": "Hierarchical Knowledge Graph edge list",
        },
        {
            "path": INFERENCE_CONFIG["nodes_csv_path"],
            "name": "nodes.csv",
            "description": "KG node metadata (used for seed chain discovery via TF-IDF)",
        },
    ]
